spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: one-day-user-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  minio:
    url: http://localhost:9000
    access-key: ${MINIO_USER}
    secret-key: ${MINIO_PASSWORD}
    bucket-name: ${MINIO_BUCKETNAME}

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false